### ISSUE TITLE
Add cadvisor and promethus to default stack

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_runtime#387]

**Comment by nh758** [comment]
Added to terraform config.

For exisitng servers we can add a simple docker-compose file and run it 
```yml
version: "3.9"

services:
  # prometheus - scrape metrics from cadvisor
  prometheus:
    image: digiserve/prometheus:main
    environment:
      - MIMIR_CLUSTER=experimental
      - MIMIR_NAMESPACE=experimental
      - MIMIR_URL=https://mimir.digiserve.org
      - MIMIR_ORG_ID=innovation
    depends_on:
      - cadvisor
   #/prometheus

  # cadvisor - collect metrics from other conatainers
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    command:
      # - '-podman="unix:///var/run/podman/podman.sock"'
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    volumes:
      - /:/rootfs:ro
      # - /var/run/user/$(id -u)/podman:/var/run/podman:ro # Use for rootless podman
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
  #/cadvisor
```
